{{- if and .Values.apiAuth.enabled (not .Values.apiAuth.existingSecret) .Values.apiAuth.apiKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hanzo-agents.apiAuth.secretName" . }}
  labels:
    {{- include "hanzo-agents.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.apiAuth.existingSecretKey }}: {{ .Values.apiAuth.apiKey | quote }}
{{- end }}

