{{- if and .Values.controlPlane.persistence.enabled (not .Values.controlPlane.persistence.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hanzo-agents.controlPlane.fullname" . }}-data
  labels:
    {{- include "hanzo-agents.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.controlPlane.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.controlPlane.persistence.size | quote }}
  {{- if .Values.controlPlane.persistence.storageClass }}
  storageClassName: {{ .Values.controlPlane.persistence.storageClass | quote }}
  {{- end }}
{{- end }}

