{{- if .Values.demoAgent.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hanzo-agents.demoAgent.fullname" . }}
  labels:
    {{- include "hanzo-agents.labels" . | nindent 4 }}
spec:
  type: {{ .Values.demoAgent.service.type }}
  selector:
    {{- include "hanzo-agents.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: demo-agent
  ports:
    - name: http
      port: {{ .Values.demoAgent.service.port }}
      targetPort: http
{{- end }}

