{{- if and .Values.postgres.enabled (not .Values.postgres.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hanzo-agents.postgres.secretName" . }}
  labels:
    {{- include "hanzo-agents.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.postgres.auth.username | quote }}
  password: {{ .Values.postgres.auth.password | quote }}
  database: {{ .Values.postgres.auth.database | quote }}
{{- end }}

